namespace Smite.Net
{
    public enum GameMode
    {
        ArenaQueue = 435,
        JoustQueued = 448,
        Conquest = 426,
        Assault = 445,
        Clash = 466,
        ConquestRanked = 451,
        JoustRanked = 450,
        MOTD = 434,
        JoustChallenge = 441,
        Siege = 459,
        Duel = 440,
        ArenaAIMedium = 468,
        JoustAIMedium = 456,
        ArenaTutorial = 462,
        ArenaChallenge = 438,
        ConquestChallenge = 429,
        ConquestAIMedium = 461,
        ArenaAIEasy = 457,
        ConquestAIEasy = 476,
        JoustAIEasy = 474,
        ConquestRankedController = 504,
        ArenaPracticeMedium = 472,
        JoustRankedController = 504,
        AssaultChallenge = 446,
        AssaultAIMedium = 454,
        JoustPracticeMedium = 472,
        ArenaPracticeEasy = 443,
        ClashChallenge = 467,
        ClashAIMedium = 469,
        AssaultAIEasy = 481,
        SiegeChallenge = 460,
        ConquestPracticeMedium = 475,
        JoustPracticeEasy = 464,
        DuelController = 502,
        ConquestPracticeEasy = 458,
        ClashAIEasy = 478,
        AssaultPracticeMedium = 480,
        AssaultPracticeEasy = 479,
        ClashPracticeMedium = 477,
        ClashPracticeEasy = 470,
        ClashTutorial = 471,
        BasicTutorial = 436
    }
}
